### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by peterrobert**
The project is ready for review

### CODE REVIEW

**Review by fatymahmed — CHANGES_REQUESTED** [review]
## Hi @peterrobert @ezeilo-su 👋👋
Your project looks good, good job on that. However, there are a few things to fix to make it look better.

**Navigation bar**
- The logo should be an image as mentioned in the [screenshot requirement from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/navbar_logo_requirement.png)
- It should have three embedded images on the rightmost part of the navbar that represent icons and/or an avatar [see the screenshot of requirement from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/icons_requirement.png).

**Video**
- It should have a share button, yours is just an icon, see [screenshot of requirement from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_share_requirement.png)
- It shows the avatar of the user who uploaded the video, please add this, see [screenshot of requirement from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_avatar_requirement.png)
- It should have a subscribe button, please add the button, see [screenshot of requirement from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/video_subscribe_requirement.png)

**Sidebar Recommended videos**
- Please add the number of views to each recommended video, see [screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/embedding_images_and_video/sidebar_views_requirement.png)

**Additional Microverse Requirements**
- You could make your README file more descriptive, you can use [this template](https://github.com/microverseinc/readme-template),
- Update your pull request description with what you have implemented so far, as advised [see screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png).
- Please check HTML markup with this validator https://validator.w3.org/#validate_by_upload, your project has some errors that you should fix, see [screenshot from Pathwright](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png). 
Screenshot

[OPTIONAL]
- I encourage you to use `<main>` tag for the dominant content of the `<body>` of a document

**Review by fatymahmed — APPROVED** [review]
### Kindly make the suggested changes and request for another code review
## Status: Changes Required.

_Feel free to reach out to me on slack (Fatima) if you any questions, I'd be happy to help_

**Review by imhta — APPROVED** [review]
# Project approved 🎉 

### Hello  @peterrobert @ezeilo-su  , 👋 You have done a great job in this project 👏 




----
### Happy coding 😄 
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__

**Comment by peterrobert** [comment]
thanks you

**Pull request closed without merging**
